version: '3.9'

services:
  demo_db:
    image: postgres
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${USER_NAME}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      TZ: Asia/Seoul
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    ports:
      - '${PORT}:5432'