import { NextUIProvider } from '@nextui-org/react'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import React from 'react'
import styled from 'styled-components'
import { wrapper } from '../store'
import { GlobalStyle } from '../styles'

const Main = styled.main`
  width: 100%;
  height: 100vh;
`

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>TODO List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
      <NextUIProvider>
        <Main>
          <Component {...pageProps} />
        </Main>
      </NextUIProvider>
    </>
  )
}

export default wrapper.withRedux(MyApp)
